export const server = "http://localhost:4010";
// export const server = "https://skill-hub-server.onrender.com"

const apiList = {
AllUserslogin : `${server}/AllUserslogin`,
Userlogin: `${server}/Userlogin`,
UserDetail: `${server}/UserloginDetails`,
forgetPassword: `${server}/forgetPassword`,
verifyOTP: `${server}/verifyOTP`,


resetPassword: `${server}/resetPassword`,
ChangePassword: `${server}/changePassword`,
getbasic: `${server}/v4/getbasic`,
addbasic:`${server}/v4/addbasic`,
subjects:`${server}/v2/subjects`,
addchapter:`${server}/v1/addchapter`,
deleteChapter:`${server}/v1/deleteChapter`,
updateChapter:`${server}/v1/updateChapter`,
addMCQ:`${server}/v1/addMCQ`,
getMCQById:`${server}/v1/getMCQById`,
updateMCQ:`${server}/v1/updateMCQ`,
deleteMCQ : `${server}/v1/deleteMCQ`,
getParagMCQById: `${server}/v2/getParagMCQById`,
update:`${server}/v2/update`,
addparaMcq:`${server}/v2/addparaMcq`,
getparamcq:`${server}/v2/getparamcq`,
delete:`${server}/v2/delete`,
subjet:`${server}/v2/subjet`,
subject:`${server}/v2/subject`,
allUsersData:`${server}/allUsersData`,
allAddInstitutes:`${server}/allAddInstitutes`,
ParticularInstitute:`${server}/ParticularInstitute`,
AddInstitute:`${server}/AddInstitute`,
deleteInstitute:`${server}/deleteInstitute`,
UpdateInstitute:`${server}/UpdateInstitute`,
individualInstitute:`${server}/individualInstitute`,
// allAddInstitutes:`${server}/allAddInstitutes`,
addBatchYear:`${server}/addBatchYear`,
updateBatchYear:`${server}/updateBatchYear`,
onselectedBatchyeardeleteinInstitutePath:`${server}/onselectedBatchyeardeleteinInstitutePath`,
addBatch:`${server}/addBatch`,
updateBatch:`${server}/updateBatch`,
onselectedBatchinBatchYearininstitutePath:`${server}/onselectedBatchinBatchYearininstitutePath`,
individualInstituteNames:`${server}/individualInstituteNames`,
individualUser:`${server}/individualUser`,
UserDetailslogin:`${server}/UserDetailslogin`,
AddUsers:`${server}/AddUsers`,
ByBatchData:`${server}/ByBatchData`,
ByListData:`${server}/ByListData`,
DisplayAllVideos:`${server}/DisplayAllVideos`,
allAddVideosData:`${server}/allAddVideosData`,
AddVideoPath:`${server}/AddVideoPath`,
deleteVideo:`${server}/deleteVideo`,
AddVideoPath:`${server}/AddVideoPath`,
foldersVideoData:`${server}/foldersVideoData`,
AddVideoFilesData:`${server}/AddVideoFilesData`,
UpdateVideosDetails:`${server}/UpdateVideosDetails`,
DisplayIndividualVideo: `${server}/DisplayIndividualVideo`,
deleteVideofiles:`${server}/deleteVideofiles`,
UpdateVideofileDetails :`${server}/UpdateVideofileDetails`,
AccessGiven :`${server}/AccessGiven`,
AccessView:`${server}/AccessView`,
Topic : `${server}/topic`,
getassessment : `${server}/getassessment`,
assessment : `${server}/assessment`,
Questions:`${server}/Questions`,
assessmentqestion : `${server}/assessmentqestion`,
getMCQs : `${server}/v1/getMCQs`,
getparamcqs : `${server}/v2/getparamcq`,
Assessmentsettings : `${server}/Assessmentsettings`,
categories : `${server}/categories`,
allBlogs : `${server}/U2/allBlogs`,
Blogs : `${server}/U2/Blogs`,
deleteblog : `${server}/U2/deleteblog`,
alllearningpathsDetails : `${server}/alllearningpathsDetails`,
getTopic : `${server}/getTopic`,
getAllContents : `${server}/getAllContents`,
addContentOfTopicsinlearningpath : `${server}/addContentOfTopicsinlearningpath`,
onselectedContentinTopicinLearningPath : `${server}/onselectedContentinTopicinLearningPath`,
updateContent : `${server}/updateContent`,
getSingledataContents : `${server}/getSingledataContents`,
addlearningpath : `${server}/addlearningpath`,
onselectedLearningPath : `${server}/onselectedLearningPath`,
updatelearningpath : `${server}/updatelearningpath`,
addTopic : `${server}/addTopic`,
onselectedTopicinLearningPath : `${server}/onselectedTopicinLearningPath`,
updateTopic : `${server}/updateTopic`,
allcategories : `${server}/v5/allcategories`,
allpractices : `${server}/v7/allpractices`,
categories1 : `${server}/v5/categories`,
practices : `${server}/v7/practices`,
categorieslist : `${server}/v5/categorieslist`,
practicelist : `${server}/v7/practicelist`,
categoriesupdate : `${server}/v5/categoriesupdate`,
practicesupdate : `${server}/v7/practicesupdate`,
practiceTest : `${server}/v6/practiceTest`,
getAllPracticeTest : `${server}/v6/getAllPracticeTest`,
deletePracticeTest : `${server}/v6/deletePracticeTest`,
getSinglePracticeTest : `${server}/v6/getSinglePracticeTest`,
getbasics : `${server}/v4/getbasics`,
deletebasic : `${server}/v4/deletebasic`,
CategorywiseAccess : `${server}/v5/CategorywiseAccess`,
PracticecategorywiseAccess : `${server}/v7/PracticecategorywiseAccess`,
addPracticetopic : `${server}/v7/addPracticetopic`,
Deletepracticetopic : `${server}/v7/Deletepracticetopic`,
editpracticetopic : `${server}/v7/editpracticetopic`,
addtestinpractice : `${server}/v7/addtestinpractice`,
deletetestinpractice : `${server}/v7/deletetestinpractice`,
getPracticeMCQById : `${server}/v7/getPracticeMCQById`,
practiceTestdata : `${server}/v7/practiceTestdata`,
GetUserdetailseperatly : `${server}/GetUserdetailseperatly`,
UpdateUserPassword : `${server}/UpdateUserPassword`,
updateUserdetails : `${server}/updateUserdetails`,
getIndiVIDUAL : `${server}/getIndiVIDUAL`,
categoriesAccessDelete : `${server}/categoriesAccessDelete`,
updateBlogs : `${server}/U2/updateBlogs`,
IndiVIDUALBlogs : `${server}/U2/IndiVIDUALBlogs`,
getcontentsdetails : `${server}/getcontentsdetails`,
testtopics:`${server}/v7/testtopics`,
practicetopics:`${server}/v7/practicetopics`,
getquestions:`${server}/v7/getquestions`,
allTesttopics:`${server}/v7/allTesttopics`,
allPracticetopics:`${server}/v7/allPracticetopics`,
getTest:`${server}/v7/getTest`,
getallquestions:`${server}/v7/getallquestions`,
categoriesUser : `${server}/v7/categories`,
deletessessment : `${server}/deletessessment`,
UserDetailstestattempts : `${server}/UserDetailstestattempts`,
AccessGivenByCategory : `${server}/AccessGivenByCategory`,
AccessGivenByTopic : `${server}/AccessGivenByTopic`,
getTestDetails : `${server}/getTestDetails`,
Pricingcategories : `${server}/Pricingcategories`,

//users apilist starts
signupdata : `${server}/signupdata`,
execute : `${server}/execute`,
getAllContentTitles : `${server}/getAllContentTitles`,
login : `${server}/login`,
UserCompilerRun : `${server}/run`,
UserCompilerStatus : `${server}/status`,
getQuestions : `${server}/getQuestions`,
getSingleVideoData : `${server}/getSingleVideoData`, 
userchangepassword : `${server}/userchangepassword`,
getassessments : `${server}/getassessments`,
assessmentquestion : `${server}/assessmentquestion`,
user : `${server}/user`,
singleLearningPath : `${server}/singleLearningPath`,
updateassessment : `${server}/updateassessment`,
getallassessments : `${server}/getallassessments`,
getassessmentscategories : `${server}/getassessmentscategories`,
coursesvideossectionwise : `${server}/coursesvideossectionwise`,
UpdatedashbordUserPassword : `${server}/UpdatedashbordUserPassword`,
getassessmentswithTitle : `${server}/getassessmentswithTitle`,
getcourseswithTitle : `${server}/getcourseswithTitle`,
getpracticeswithTitle : `${server}/v7/getpracticeswithTitle`,
submitAssessmentAnswers : `${server}/submitAssessmentAnswers`,
getTestAssessmentDetails : `${server}/getTestAssessmentDetails`,
getTestAssessmentDetailsalldescendingorder : `${server}/getTestAssessmentDetailsalldescendingorder`,
getassessmentTitlewise: `${server}/getassessmentTitlewise`,
getallassessmentquestionsTitlewiseforcertification:`${server}/getallassessmentquestionsTitlewiseforcertification`,
submitAssignmentforcertification:`${server}/submitAssignmentforcertification`,
getTestcertificationDetails:`${server}/getTestcertificationDetails`,

};

export default apiList;

  
